server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service/
          predicates:
            - Path=/users/**